#ifndef ENGPAR_TYPES_H
#define ENGPAR_TYPES_H

#define ENGPAR_GID_T   int64_t
#define ENGPAR_GID_FT  C_INT64_T
#define ENGPAR_LID_T   LOCAL_ID_TYPE
#define ENGPAR_LID_FT  LOCAL_ID_FTYPE
#define ENGPAR_WGT_T   double
#define ENGPAR_WGT_FT  C_DOUBLE
#define ENGPAR_PART_T  int32_t
#define ENGPAR_PART_FT C_INT32_T
#define ENGPAR_EDGE_T  LOCAL_ID_TYPE
#define ENGPAR_EDGE_FT LOCAL_ID_FTYPE

#endif
