set(CTEST_PROJECT_NAME "EnGPar")
set(CTEST_NIGHTLY_START_TIME "20:00:00 EST")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "my.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=EnGPar")
set(CTEST_DROP_SITE_CDASH TRUE)
